---
- hosts: all
  become: yes
  tasks:
  - name: Update Repos
    apt:
      update_cache: yes
  - name: Install Debian Updates
    apt:
      upgrade: dist
      autoclean: yes
      autoremove: yes
  - name: reboot
    reboot:
  - name: Add Docker Key
    apt_key:
      url: https://download.docker.com/linux/debian/gpg
      state: present
  - name: Add Docker Repo
    apt_repository:
      repo: 'deb [arch=amd64] https://download.docker.com/linux/debian buster stable'
      state: present
      filename: docker
  - name: Update Repos
    apt:
      update_cache: yes
  - name: Kali Metapackage install
    apt:
      name: kali-linux-all
      state: latest
  - name: Install Empire
    apt:
      name: powershell-empire
      state: latest
  - name: Install VSCode
    apt:
      deb: https://go.microsoft.com/fwlink/?LinkID=760868
  - name: Install Atom
    apt:
      deb: https://atom.io/download/deb
  - name: install Dependancies
    apt:
      name:
        - dkms
        - docker
        - docker-compose
        - libssl1.0-dev
        - libffi-dev
        - python-dev
        - python-pip
        - build-essential
        - swig
        - tcpdump
        - python-virtualenv
        - python3-pip
        - python-pip
      state: latest
  - name: Make Drivers directory
    file:
      path: /opt/drivers
      state: directory
  - name: Make Tools directory
    file:
      path: /opt/toolz
      state: directory
  - name: Download the Alfa Drivers
    script: ./alfa.sh
  - name: Download Silent Trinity
    script: ./silenttrinity.sh
  - name: Enable Docker service
    service:
      name: docker
      enabled: yes
  - name: Start Docker service
    service:
      name: docker
      state: started
  - name: Install pupy
    script: ./pupy.sh
  - name: "Make Ghidra directory"
    file:
      path: /opt/toolz/ghidra
      state: directory
  - name: "Install Ghidra"
    unarchive:
      src: https://ghidra-sre.org/ghidra_9.1.2_PUBLIC_20200212.zip
      dest: /opt/toolz/ghidra
      remote_src: yes