---
- hosts: all
  become: yes
  tasks:
  - name: Install RHEL updates
    yum:
      name: '*'
      state: latest
    when: ansible_facts['os_family']|lower == 'redhat'
  - name: Clean up RHEL machines
    yum:
      autoremove: yes
    when: ansible_facts['os_family']|lower == 'redhat'
  - name: Install Debian Updates
    apt:
      upgrade: dist
      autoclean: yes
      autoremove: yes
    when: ansible_facts['os_family']|lower == 'debian'
  